const kb = require('./keyboard-buttons')

module.exports = {
main_menu:[
    [kb.main_menuPage.all_menus_btn,kb.main_menuPage.pizza_btn],
    [kb.main_menuPage.drinks,kb.main_menuPage.fast_food],
    [kb.main_menuPage.basket]
],
    main_menuSecret:[
    [kb.main_menuPage.all_menus_btn,kb.main_menuPage.pizza_btn],
    [kb.main_menuPage.drinks,kb.main_menuPage.fast_food],
    [kb.main_menuPage.basket,kb.main_menuPage_Secret.adminPanel]
],
    adminFunc:[
      [kb.adminPanelPage.sendToAll],
      [kb.adminPanelPage.addUser,kb.adminPanelPage.deleteUser],
      [kb.adminPanelPage.admins],
      [kb.back]
    ],
    sharesPage:[
        [kb.shares.create],
        [kb.back]
    ],
    dough_heightPage:[
    [kb.doughPage.height.subtle,kb.doughPage.height.fat],
    [kb.back]
    ],
    energize_page:[
      [kb.drinksPage.energize.eighteen_plus.name,kb.drinksPage.energize.flash.name],
      [kb.drinksPage.energize.red_bull.name],
       [kb.back,kb.mainMenu]
    ],
    dough_sizePage:[
        [kb.doughPage.size.medium,kb.doughPage.size.maximum],
        [kb.back,kb.mainMenu]
    ],
    pizzaPage:[
        [kb.pizzaPage.pizza_1.name,kb.pizzaPage.pizza_2.name],
        [kb.pizzaPage.pizza_3.name,kb.pizzaPage.pizza_10.name],
        [kb.pizzaPage.pizza_5.name,kb.pizzaPage.pizza_4.name],
        [kb.pizzaPage.pizza_7.name,kb.pizzaPage.pizza_8.name],
        [kb.pizzaPage.pizza_9.name,kb.pizzaPage.pizza_6.name],
        [kb.pizzaPage.pizza_11.name,kb.pizzaPage.pizza_12.name],
        [kb.pizzaPage.pizza_13.name,kb.pizzaPage.pizza_14.name],
        [kb.pizzaPage.pizza_15.name,kb.pizzaPage.pizza_16.name],
        [kb.pizzaPage.pizza_17.name,kb.pizzaPage.pizza_18.name],
        [kb.pizzaPage.pizza_19.name,kb.pizzaPage.pizza_20.name],
        [kb.pizzaPage.pizza_21.name],
        [kb.back,kb.mainMenu,kb.main_menuPage.basket]
    ],
    counterPage:[
        [kb.counter.one,kb.counter.two,kb.counter.three],
        [kb.counter.four,kb.counter.five,kb.counter.six],
        [kb.counter.seven,kb.counter.eight,kb.counter.nine],
        [kb.back,kb.mainMenu,kb.main_menuPage.basket]
    ],
    fast_food:[
        [kb.fast_foodPage.hamburger.name,kb.fast_foodPage.subway_sandwich.name],
        [kb.fast_foodPage.cheese_burger.name,kb.fast_foodPage.club_sandwich.name],
        [kb.fast_foodPage.fries_potatoes.name],
        [kb.back]
    ],
    drinks:[
        [kb.drinksPage.fresh.name,kb.drinksPage.coffee.name],
        [kb.drinksPage.energize.name],
        [kb.back]
    ],
    drinks_hot:[
        [kb.drinksPage.coffee.hot.americano.name,kb.drinksPage.coffee.hot.latte.name],
        [kb.drinksPage.coffee.hot.capuchino.name,kb.drinksPage.coffee.hot.grand_capuchino.name],
        [kb.back,kb.mainMenu]
    ],
    drinks_fresh:[
      [kb.drinksPage.fresh.cola.name,kb.drinksPage.fresh.fanta.name],
      [kb.drinksPage.fresh.sprite.name,kb.drinksPage.fresh.water.name],
       [kb.drinksPage.fresh.juice.name],
        [kb.back,kb.mainMenu]
    ],
    first:[
        [{text:kb.takePage.first.phone,request_contact:true}],
        [kb.back]
    ],
    second:[
        [{text:kb.takePage.second.location,request_location:true}],
        [kb.back]
    ]
}